### ISSUE TITLE
Text input widget chops off the bottom of the text

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10692]
e.g. quickly
![image](https://github.com/user-attachments/assets/9e0c4d32-243c-4315-b230-f1c0aef5a3fa)

**Comment by kazcw** [comment]
I can't reproduce this. I tested on OS X (current `develop`) and Windows (recent nightly); I'm not seeing any truncation. The text input widget also seems to be in a different font.

**Comment by Frizi** [comment]
This likely got fixed with changed layouts of widgets. The input box height matches the port height for a while already, So I'm pretty certain this can be closed as fixed now.

**Comment by AdRiley** [comment]
I am still seeing this on Windows. Works fine on my mac.

![image](https://github.com/user-attachments/assets/21cc7329-4757-4f57-adf8-412ac881afac)

Version 2024.4.1-rc6
Build 570cb8a9421005f6456582696fbf959aed5a52c2
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.4.1-rc6 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by Frizi** [comment]
I experimented with CSS a bit, and everything seems to be correct on that front. The text is just cut off by various amounts on various font scaling settings, but nothing looks good. I think this might be the "Enso" font issue, as changing fonts to anything else immediately fixes the issue.

**Comment by farmaazon** [comment]
>  I think this might be the "Enso" font issue

> I can't reproduce this. I tested on OS X (current develop) and Windows (recent nightly); I'm not seeing any truncation. The text input widget also seems to be in a different font.

Does it mean that we use different fonts on different platforms?

**Comment by kazcw** [comment]
> > I think this might be the "Enso" font issue
> 
> > I can't reproduce this. I tested on OS X (current develop) and Windows (recent nightly); I'm not seeing any truncation. The text input widget also seems to be in a different font.
> 
> Does it mean that we use different fonts on different platforms?

I think it is actually the same font. I expected the first image said "quickly", in which case the rounded "y" would indicate a different font from the other images, but actually it probably says "quicklu".

**Comment by farmaazon** [comment]
Because Enso font is hard to fix, and MPLUS1 seems to have alignment issues in our app, some research should be done for an alternative font.
