### ISSUE TITLE
Running tests leaves a leftover C:\temp\test_cleaning on Linux

### ISSUE THREAD

**Issue by Procrat** [enso-org/enso#6010]
### Discord username

Stijn#6455

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Running all tests creates a file called `C:\\temp\\test_cleaning/` in the `build/ci_utils` directory. Presumably, this works on Windows, but this is occurring on Linux.

### Expected behaviour

If intentional, I expect that directory to be cleaned up after the tests are finished.

### How we can reproduce it?

`./run wasm test`

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by vitvakatu** [comment]
Can confirm it also happens on Mac OS.

**Comment by wdanilo** [comment]
CC @mwu-tow, I thought it was fixed already – I remember we had discussion about it long time ago. Is this a new reappearance of the same issue?

**Comment by mwu-tow** [comment]
@wdanilo, I have no idea what happened here. Yes, we discussed this, and I vaguely remember fixing this. But obviously, it is not fixed. I'll do that today (unless someone else wants); this is a one-liner.

**Comment by wdanilo** [comment]
Perfect, thanks @mwu-tow !

**Comment by mwu-tow** [comment]
Was fixed https://github.com/enso-org/enso/pull/6055
