### ISSUE TITLE
Opened projects are empty

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#7284]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening a project (new or old does not matter), the IDE stays blank.

### Expected behaviour

The project should open. 

### How we can reproduce it?

Run IDE with `./run ide watch --skip-wasm-opt  --ide-option -debug.dev-tools=true --ide-option -debug --backend-source release --backend-release latest --ide-option `
Create a new project
Open the project

### Logs

There are many errors about the shader compilation in the developer console:
![image](https://github.com/enso-org/enso/assets/1428930/22b704f8-0e12-4eff-8f00-cf24f970a574)

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Manjaro

**Comment by MichaelMauderer** [comment]
I will be opening a PR to fix this in a few minutes. It seems this is fixed by a bump of the electron version.

**Comment by Akirathan** [comment]
Reopening the issue, since I can still reproduce it on all the nightly AppImages that I have locally (on the screenshot):
![image](https://github.com/enso-org/enso/assets/14013887/504417c1-5cd5-4928-80af-e8ae4b7baed5)

And also on my local build `run ide build` from 07-21.

Running the AppImage with `-window=false` and attaching with my browser works as expected. My once I try to open or create any project in the electron app, I just have a blank screen with the same errors on the console mentioned in the issue description.

My Specs:
```
Fedora 38
Kernel 6.4.6-200
Thinkpad P1 Gen 4
CPU:  Intel i7-11800H 11th Gen
GPU:  NVIDIA Quadro RTX A2000 4GB VRAM
```

**Comment by farmaazon** [comment]
Another bump is required. I've already done it in #7350 .

**Comment by kazcw** [comment]
This problem presented a bit differently on my machine (Linux); I'll note it here in case something like this happens again:
- The Electron IDE opens blank. Devtools can be opened (either with the shortcut or the CLI option), but the devtools window is also blank.
- The problem started occurring for all new builds, even of old versions. Old builds of old versions still work.
- The problem is fixed by the electron version bump in #7441.

**Comment by somebody1234** [comment]
Oh, so *this* is what I ran into last week (the shader issue mentioned in the OP, also Linux).
For some reason, the next day it was working fine again.

(For posterity: the error message in the screenshot is "Unable to compile shader program".)
